log_level: Info
# camera_type: hik
camera_type: video
# camera_type: galaxy
camera_name: camera0
camera_frame_id: camera
image_publish_interval_ms: 0
cam_info_publish_interval_ms: 1000
max_exit_fail_count: 100
reverse_xy: true
# video_path: assets/big_buff.avi
# video_path: assets/demo.avi
video_path: assets/buff_test_1.avi
camera_info:
  view_width_px: 1440
  view_height_px: 1080
  camera_matrix: [2411.932469, 0.0, 713.916764, 0.0, 2411.465577, 519.494149, 0.0, 0.0, 1.0]
  distortion_coefficients: [-0.093204, 0.153681, 0.000112, -0.000588, 0.0]
camera_params:
  exposure_time: 3000
  gain: 15.0
  frame_rate: 100
