set(FIRE_CONTROL_SYSTEM_PLUGIN_TARGET fire_control_system_plugin_lib)
add_library(${FIRE_CONTROL_SYSTEM_PLUGIN_TARGET} SHARED src/PlannerControl.cpp)
target_include_directories(${FIRE_CONTROL_SYSTEM_PLUGIN_TARGET} PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}/include)
target_link_libraries(${FIRE_CONTROL_SYSTEM_PLUGIN_TARGET} PUBLIC app_interface_lib class_loader_lib google_logger_lib)
