// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "Time_generated.h"

namespace foxglove {

struct CarData;
struct CarDataBuilder;

struct CarData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef CarDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODE = 4,
    VT_MY_COLOR = 6,
    VT_YAW = 8,
    VT_PITCH = 10,
    VT_ROLL = 12,
    VT_BACK_YAW = 14,
    VT_MY_BLOOD = 16,
    VT_V_YAW = 18,
    VT_V_PITCH = 20,
    VT_YAW_OFFSET = 22,
    VT_PITCH_OFFSET = 24,
    VT_BULLET_SPEED = 26,
    VT_DUNE = 28
  };
  uint8_t mode() const {
    return GetField<uint8_t>(VT_MODE, 0);
  }
  bool mutate_mode(uint8_t _mode = 0) {
    return SetField<uint8_t>(VT_MODE, _mode, 0);
  }
  uint8_t my_color() const {
    return GetField<uint8_t>(VT_MY_COLOR, 0);
  }
  bool mutate_my_color(uint8_t _my_color = 0) {
    return SetField<uint8_t>(VT_MY_COLOR, _my_color, 0);
  }
  float yaw() const {
    return GetField<float>(VT_YAW, 0.0f);
  }
  bool mutate_yaw(float _yaw = 0.0f) {
    return SetField<float>(VT_YAW, _yaw, 0.0f);
  }
  float pitch() const {
    return GetField<float>(VT_PITCH, 0.0f);
  }
  bool mutate_pitch(float _pitch = 0.0f) {
    return SetField<float>(VT_PITCH, _pitch, 0.0f);
  }
  float roll() const {
    return GetField<float>(VT_ROLL, 0.0f);
  }
  bool mutate_roll(float _roll = 0.0f) {
    return SetField<float>(VT_ROLL, _roll, 0.0f);
  }
  uint16_t back_yaw() const {
    return GetField<uint16_t>(VT_BACK_YAW, 0);
  }
  bool mutate_back_yaw(uint16_t _back_yaw = 0) {
    return SetField<uint16_t>(VT_BACK_YAW, _back_yaw, 0);
  }
  uint8_t my_blood() const {
    return GetField<uint8_t>(VT_MY_BLOOD, 0);
  }
  bool mutate_my_blood(uint8_t _my_blood = 0) {
    return SetField<uint8_t>(VT_MY_BLOOD, _my_blood, 0);
  }
  float v_yaw() const {
    return GetField<float>(VT_V_YAW, 0.0f);
  }
  bool mutate_v_yaw(float _v_yaw = 0.0f) {
    return SetField<float>(VT_V_YAW, _v_yaw, 0.0f);
  }
  float v_pitch() const {
    return GetField<float>(VT_V_PITCH, 0.0f);
  }
  bool mutate_v_pitch(float _v_pitch = 0.0f) {
    return SetField<float>(VT_V_PITCH, _v_pitch, 0.0f);
  }
  int8_t yaw_offset() const {
    return GetField<int8_t>(VT_YAW_OFFSET, 0);
  }
  bool mutate_yaw_offset(int8_t _yaw_offset = 0) {
    return SetField<int8_t>(VT_YAW_OFFSET, _yaw_offset, 0);
  }
  int8_t pitch_offset() const {
    return GetField<int8_t>(VT_PITCH_OFFSET, 0);
  }
  bool mutate_pitch_offset(int8_t _pitch_offset = 0) {
    return SetField<int8_t>(VT_PITCH_OFFSET, _pitch_offset, 0);
  }
  float bullet_speed() const {
    return GetField<float>(VT_BULLET_SPEED, 0.0f);
  }
  bool mutate_bullet_speed(float _bullet_speed = 0.0f) {
    return SetField<float>(VT_BULLET_SPEED, _bullet_speed, 0.0f);
  }
  uint8_t dune() const {
    return GetField<uint8_t>(VT_DUNE, 0);
  }
  bool mutate_dune(uint8_t _dune = 0) {
    return SetField<uint8_t>(VT_DUNE, _dune, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_MODE, 1) &&
           VerifyField<uint8_t>(verifier, VT_MY_COLOR, 1) &&
           VerifyField<float>(verifier, VT_YAW, 4) &&
           VerifyField<float>(verifier, VT_PITCH, 4) &&
           VerifyField<float>(verifier, VT_ROLL, 4) &&
           VerifyField<uint16_t>(verifier, VT_BACK_YAW, 2) &&
           VerifyField<uint8_t>(verifier, VT_MY_BLOOD, 1) &&
           VerifyField<float>(verifier, VT_V_YAW, 4) &&
           VerifyField<float>(verifier, VT_V_PITCH, 4) &&
           VerifyField<int8_t>(verifier, VT_YAW_OFFSET, 1) &&
           VerifyField<int8_t>(verifier, VT_PITCH_OFFSET, 1) &&
           VerifyField<float>(verifier, VT_BULLET_SPEED, 4) &&
           VerifyField<uint8_t>(verifier, VT_DUNE, 1) &&
           verifier.EndTable();
  }
};

struct CarDataBuilder {
  typedef CarData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mode(uint8_t mode) {
    fbb_.AddElement<uint8_t>(CarData::VT_MODE, mode, 0);
  }
  void add_my_color(uint8_t my_color) {
    fbb_.AddElement<uint8_t>(CarData::VT_MY_COLOR, my_color, 0);
  }
  void add_yaw(float yaw) {
    fbb_.AddElement<float>(CarData::VT_YAW, yaw, 0.0f);
  }
  void add_pitch(float pitch) {
    fbb_.AddElement<float>(CarData::VT_PITCH, pitch, 0.0f);
  }
  void add_roll(float roll) {
    fbb_.AddElement<float>(CarData::VT_ROLL, roll, 0.0f);
  }
  void add_back_yaw(uint16_t back_yaw) {
    fbb_.AddElement<uint16_t>(CarData::VT_BACK_YAW, back_yaw, 0);
  }
  void add_my_blood(uint8_t my_blood) {
    fbb_.AddElement<uint8_t>(CarData::VT_MY_BLOOD, my_blood, 0);
  }
  void add_v_yaw(float v_yaw) {
    fbb_.AddElement<float>(CarData::VT_V_YAW, v_yaw, 0.0f);
  }
  void add_v_pitch(float v_pitch) {
    fbb_.AddElement<float>(CarData::VT_V_PITCH, v_pitch, 0.0f);
  }
  void add_yaw_offset(int8_t yaw_offset) {
    fbb_.AddElement<int8_t>(CarData::VT_YAW_OFFSET, yaw_offset, 0);
  }
  void add_pitch_offset(int8_t pitch_offset) {
    fbb_.AddElement<int8_t>(CarData::VT_PITCH_OFFSET, pitch_offset, 0);
  }
  void add_bullet_speed(float bullet_speed) {
    fbb_.AddElement<float>(CarData::VT_BULLET_SPEED, bullet_speed, 0.0f);
  }
  void add_dune(uint8_t dune) {
    fbb_.AddElement<uint8_t>(CarData::VT_DUNE, dune, 0);
  }
  explicit CarDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<CarData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<CarData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<CarData> CreateCarData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t mode = 0,
    uint8_t my_color = 0,
    float yaw = 0.0f,
    float pitch = 0.0f,
    float roll = 0.0f,
    uint16_t back_yaw = 0,
    uint8_t my_blood = 0,
    float v_yaw = 0.0f,
    float v_pitch = 0.0f,
    int8_t yaw_offset = 0,
    int8_t pitch_offset = 0,
    float bullet_speed = 0.0f,
    uint8_t dune = 0) {
  CarDataBuilder builder_(_fbb);
  builder_.add_bullet_speed(bullet_speed);
  builder_.add_v_pitch(v_pitch);
  builder_.add_v_yaw(v_yaw);
  builder_.add_roll(roll);
  builder_.add_pitch(pitch);
  builder_.add_yaw(yaw);
  builder_.add_back_yaw(back_yaw);
  builder_.add_dune(dune);
  builder_.add_pitch_offset(pitch_offset);
  builder_.add_yaw_offset(yaw_offset);
  builder_.add_my_blood(my_blood);
  builder_.add_my_color(my_color);
  builder_.add_mode(mode);
  return builder_.Finish();
}

inline const foxglove::CarData *GetCarData(const void *buf) {
  return ::flatbuffers::GetRoot<foxglove::CarData>(buf);
}

inline const foxglove::CarData *GetSizePrefixedCarData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foxglove::CarData>(buf);
}

inline CarData *GetMutableCarData(void *buf) {
  return ::flatbuffers::GetMutableRoot<CarData>(buf);
}

inline foxglove::CarData *GetMutableSizePrefixedCarData(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<foxglove::CarData>(buf);
}

inline bool VerifyCarDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<foxglove::CarData>(nullptr);
}

inline bool VerifySizePrefixedCarDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<foxglove::CarData>(nullptr);
}

inline void FinishCarDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CarData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedCarDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::CarData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_CARDATA_FOXGLOVE_H_
