// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VISIONDATA_FOXGLOVE_H_
#define FLATBUFFERS_GENERATED_VISIONDATA_FOXGLOVE_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace foxglove {

struct VisionData;
struct VisionDataBuilder;

struct VisionData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VisionDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MODE = 4,
    VT_YAW = 6,
    VT_PITCH = 8,
    VT_IS_FIND_TARGET = 10,
    VT_BACK_IS_FIND_TARGET = 12,
    VT_FIRE_CNT = 14,
    VT_TIMING = 16
  };
  uint8_t mode() const {
    return GetField<uint8_t>(VT_MODE, 0);
  }
  bool mutate_mode(uint8_t _mode = 0) {
    return SetField<uint8_t>(VT_MODE, _mode, 0);
  }
  float yaw() const {
    return GetField<float>(VT_YAW, 0.0f);
  }
  bool mutate_yaw(float _yaw = 0.0f) {
    return SetField<float>(VT_YAW, _yaw, 0.0f);
  }
  float pitch() const {
    return GetField<float>(VT_PITCH, 0.0f);
  }
  bool mutate_pitch(float _pitch = 0.0f) {
    return SetField<float>(VT_PITCH, _pitch, 0.0f);
  }
  uint8_t is_find_target() const {
    return GetField<uint8_t>(VT_IS_FIND_TARGET, 0);
  }
  bool mutate_is_find_target(uint8_t _is_find_target = 0) {
    return SetField<uint8_t>(VT_IS_FIND_TARGET, _is_find_target, 0);
  }
  uint8_t back_is_find_target() const {
    return GetField<uint8_t>(VT_BACK_IS_FIND_TARGET, 0);
  }
  bool mutate_back_is_find_target(uint8_t _back_is_find_target = 0) {
    return SetField<uint8_t>(VT_BACK_IS_FIND_TARGET, _back_is_find_target, 0);
  }
  uint8_t fire_cnt() const {
    return GetField<uint8_t>(VT_FIRE_CNT, 0);
  }
  bool mutate_fire_cnt(uint8_t _fire_cnt = 0) {
    return SetField<uint8_t>(VT_FIRE_CNT, _fire_cnt, 0);
  }
  uint16_t timing() const {
    return GetField<uint16_t>(VT_TIMING, 0);
  }
  bool mutate_timing(uint16_t _timing = 0) {
    return SetField<uint16_t>(VT_TIMING, _timing, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_MODE, 1) &&
           VerifyField<float>(verifier, VT_YAW, 4) &&
           VerifyField<float>(verifier, VT_PITCH, 4) &&
           VerifyField<uint8_t>(verifier, VT_IS_FIND_TARGET, 1) &&
           VerifyField<uint8_t>(verifier, VT_BACK_IS_FIND_TARGET, 1) &&
           VerifyField<uint8_t>(verifier, VT_FIRE_CNT, 1) &&
           VerifyField<uint16_t>(verifier, VT_TIMING, 2) &&
           verifier.EndTable();
  }
};

struct VisionDataBuilder {
  typedef VisionData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_mode(uint8_t mode) {
    fbb_.AddElement<uint8_t>(VisionData::VT_MODE, mode, 0);
  }
  void add_yaw(float yaw) {
    fbb_.AddElement<float>(VisionData::VT_YAW, yaw, 0.0f);
  }
  void add_pitch(float pitch) {
    fbb_.AddElement<float>(VisionData::VT_PITCH, pitch, 0.0f);
  }
  void add_is_find_target(uint8_t is_find_target) {
    fbb_.AddElement<uint8_t>(VisionData::VT_IS_FIND_TARGET, is_find_target, 0);
  }
  void add_back_is_find_target(uint8_t back_is_find_target) {
    fbb_.AddElement<uint8_t>(VisionData::VT_BACK_IS_FIND_TARGET, back_is_find_target, 0);
  }
  void add_fire_cnt(uint8_t fire_cnt) {
    fbb_.AddElement<uint8_t>(VisionData::VT_FIRE_CNT, fire_cnt, 0);
  }
  void add_timing(uint16_t timing) {
    fbb_.AddElement<uint16_t>(VisionData::VT_TIMING, timing, 0);
  }
  explicit VisionDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VisionData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VisionData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VisionData> CreateVisionData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint8_t mode = 0,
    float yaw = 0.0f,
    float pitch = 0.0f,
    uint8_t is_find_target = 0,
    uint8_t back_is_find_target = 0,
    uint8_t fire_cnt = 0,
    uint16_t timing = 0) {
  VisionDataBuilder builder_(_fbb);
  builder_.add_pitch(pitch);
  builder_.add_yaw(yaw);
  builder_.add_timing(timing);
  builder_.add_fire_cnt(fire_cnt);
  builder_.add_back_is_find_target(back_is_find_target);
  builder_.add_is_find_target(is_find_target);
  builder_.add_mode(mode);
  return builder_.Finish();
}

inline const foxglove::VisionData *GetVisionData(const void *buf) {
  return ::flatbuffers::GetRoot<foxglove::VisionData>(buf);
}

inline const foxglove::VisionData *GetSizePrefixedVisionData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<foxglove::VisionData>(buf);
}

inline VisionData *GetMutableVisionData(void *buf) {
  return ::flatbuffers::GetMutableRoot<VisionData>(buf);
}

inline foxglove::VisionData *GetMutableSizePrefixedVisionData(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<foxglove::VisionData>(buf);
}

inline bool VerifyVisionDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<foxglove::VisionData>(nullptr);
}

inline bool VerifySizePrefixedVisionDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<foxglove::VisionData>(nullptr);
}

inline void FinishVisionDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::VisionData> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedVisionDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<foxglove::VisionData> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace foxglove

#endif  // FLATBUFFERS_GENERATED_VISIONDATA_FOXGLOVE_H_
