log_level: Info
plot_info: true
show_image: true
always_on_task_small_buff: false
always_on_task_big_buff: true
tf_query_tolerance_ms: 200.0
cmd_pub_dt_sec: 0.005
predict_offset_ms: 70
camera_name: camera0
odom_frame_id: odom
camera_frame_id: camera
buff_blade_topic:
  service: runes
  instance: detector
  event: data
serial_topic:
  service: aim_command
  instance: tracker
  event: data

small_buff_conf:
  lost_threshold_sec: 0.8
  match_conf:
    max_match_distance_m: 1.0
    max_match_roll_diff_degree: 30.0
  blade_conf:
    pixel_error:
      x: 5.0
      y: 5.0
    position_noise_m:
      x: 0.03
      y: 0.03
      z: 0.03
    roll_noise_degree: 2.0
  center_conf:
    position_consistency_noise_m:
      x: 0.01
      y: 0.01
      z: 0.01
    roll_noise_degree: 3.0
    vroll_noise_rad: 0.10
    position_prior_noise_m:
      x: 0.10
      y: 0.10
      z: 0.10
    roll_prior_noise_degree: 30.0
    vroll_prior_noise_rad: 6.0

big_buff_conf:
  fitter_conf:
    queue_upper_limit: 200
    queue_lower_limit: 100
    param_lower_bound_scale: 1.0
    param_upper_bound_scale: 1.0
    curve_fitting_interval_time_ms: 20
  lost_threshold_sec: 1.0
  match_conf:
    max_match_distance_m: 1.0
    max_match_roll_diff_degree: 30.0
  blade_conf:
    pixel_error:
      x: 5.0
      y: 5.0
    position_noise_m:
      x: 0.03
      y: 0.03
      z: 0.03
    roll_noise_degree: 2.0
  center_conf:
    position_consistency_noise_m:
      x: 0.01
      y: 0.01
      z: 0.01
    roll_noise_degree: 3.0
    vroll_noise_rad: 0.10
    position_prior_noise_m:
      x: 0.10
      y: 0.10
      z: 0.10
    roll_prior_noise_degree: 30.0
    vroll_prior_noise_rad: 6.0

trajectory_conf:
  ballistic_conf:
    g: 9.8
    k: 0.005
    barrel_length: 0.08
    time_step: 0.01
    max_fly_time: 1.0
    max_pitch_iterate_count: 100
    min_pitch_error_m: 0.01
    gimbal_pitch_min_degree: -30.0
    gimbal_pitch_max_degree: 30.0
  max_aim_iterate_count: 20
  aim_ok_error_m: 0.005
  blade_select_change_count_thres: 20
  fail_polling_interval_sec: 0.1
  min_bullet_speed: 18
  max_bullet_speed: 25
  default_bullet_speed: 22
  iterative_fly_time: true
  yaw_offset: 0.0
  pitch_offset: 0.0
