target("tools")
set_kind("static")
add_includedirs(".", { public = true })
add_files("src/*.cpp")
add_packages("opencv")
add_packages("eigen")
add_packages("yaml-cpp")
add_deps("common_defs")
add_packages("fmt")
add_packages("nameof")
add_packages("quill")
add_packages("nlohmann_json")
add_deps("fast_tf")
add_packages("reflect-cpp")
add_rules("iceoryx_deps")
add_links("atomic")
target_end()
