log_level: Info
render_interval_ms: 10
coord_conf:
  frame_size: 1.0
  # frame_ids: [odom, camera]
  frame_ids: [odom]
  static_frame_id: odom
  tf_query_time_tolerance_ms: 100
  draw_frame_trajectory: false
  trajectory_frame_id: "odom"
  draw_camera_visualization: false
  camera_name: "camera0"
  camera_frame_id: "camera"
armor_conf:
  fixed_frame_id: odom
  tf_query_time_tolerance_ms: 100
  path_to_armor_stl: assets/armor_small.stl
  service_instance_event: [armors, fake_ap, data]
  # service_instance_event: [armors, detector, data]
  armor_scale: 0.002
# target_conf:
#   msg_source:
#     service: target
#     instance: fake_tp
#     event: data
#   show_vel_arrow: true
#   target_scale: 0.1
#   arrow_scale: 0.1
