log_level: Info
camera_params:
  exposure_time: 3000
  gain: 15.0
  frame_rate: -1.0
use_muti_thread: true
queue_size: 4
detect_when_idle: true
use_pca: true
show_detect_result: true
show_optimize_result: true
show_pnp_result: true
plot_pnp_result: true
all_is_three: false
step_by_step_debug: false
default_enemy_color: Blue
update_enemy_color: true
camera_name: camera0
armors_topic:
  service: armors
  instance: detector
  event: data
yolo_version: YOLOv5
yolo_conf:
  device: CPU
  model_path: assets/0526.onnx
  use_latency_performancemode: false
  score_thresh: 0.7
  nms_iou_thresh: 0.3
  accept_thresh: 0.8
pca_conf:
  pass_optimize_lightbar_width: 3
  normalize_max_brightness: 25.0
  lightbar_min_mean_brightness: 30.0
  padding_scale: 0.07
  search_start_ratio: 0.4
  search_end_ratio: 0.6
pnp_conf:
  use_generic_mode: false
  project_error_ratio_thres: 3.0
  roll_thres_degree: 15.0
  frame_axes_length: 0.1
  outpost_is_small_armor: true
