mode: auto_buff
enemy_color: red
bullet_speed: 20.5

serial:
  enable: true
  device_name: /dev/gimbal
  baud_rate: 115200
  char_size: 8
  read_buf_size: 4096
serial_send_to_image_microseconds: 0
use_sim: true

record:
 enable: false

tf:
  # camera_in_gimbal:
  #   t: [0.0, 0.0, 0.02]
  #   R: [1.0, 0.0, 0.0,
  #     0.0, 1.0, 0.0,
  #     0.0, 0.0, 1.0]
  # shoot_in_gimbal:
  #   t: [0.2,0.0,0.0]
  #   R: [1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0]
  camera_in_gimbal:
    t: [0.110750382, 0.0, 0.0522]
    R: [1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0]

  shoot_in_gimbal:
    t: [0.04375, 0.0, 0.0]
    R: [1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0]
wheel_odometry:
  q_xyz: [10.0,10.0,1.0]
  r_vxyz: [0.05,0.05,0.05]

bullet_pick_up:
  ballistic_trajectory:
    gravity: 9.8
    resistance: 0.001
  
auto_exposure:
  enable: false
  target_brightness: 35.0
  tolerance: 3.0
  step_gain: 15.0
  decay_step: 1.0
  exposure_min: 100.0
  exposure_max: 3500.0
  control_interval_ms: 300


armor_detector:
  max_infer_num: 3
  backend: openvino
  net_detector:
    openvino:
      model_path: ${ROOT_DIR}/model/0526.onnx
      device_name: "GPU"
      perf_mode: "THROUGHPUT"
      priority: "HIGH"
      # scheduling_core_type: "PCORE_ONLY"
      execution_mode: "PERFORMANCE"
      infer_request_buffer_num: 10
    tensorrt:
      model_path: ${ROOT_DIR}/model/opt-1208-001.onnx
      copy_context_num: 3
      min_free_mem_ratio: 0.1
      use_cuda_preproces: true
    armor_infer:
      model_type: rp
      conf_threshold: 0.2
  number_classifier:
    enable: true
    model_path: ${ROOT_DIR}/model/mlp_finetuned.onnx
    label_path: ${ROOT_DIR}/model/label.txt
  color_classifier:
    enable: true
    diff_threshold: 20.0
  cv:
    light:
      bin_threshold: 120.0
      min_wh_ratio: 0.001
      max_wh_ratio: 0.4
      max_angle: 40.0
    armor:
      min_ratio: 0.8
      max_ratio: 5.0

      
armor_tracker:
  lost_time_thres: 1.5
  lost_time_thres_outpost: 2.0
  tracking_thres: 2
  qxyz_common: [30.0, 30.0, 1.0]
  qyaw_common: 30.0
  qxyz_output: [1.0, 1.0, 1.0]
  qyaw_output: 0.01
  q_r: 0.0000001
  q_l: 0.0000001
  q_h: 0.0000001
  q_wpr: 0.1
  q_outpost_dz: 0.0000001
  enable_lights_measure: true
  armor_match_gate: 200.0
  armor_match_gate_not_all_init: 1000.0
  armor_match_w_center_err: 5.0
  armor_match_w_angle_err: 10.0
  armor_match_w_side_length_err: 1.0
  light_match_length_ratio_gate: 0.2
  light_match_angle_gate: 0.2
  light_match_pos_gate_by_length_ratio: 5.0
  r_sigma_px_by_length_ratio: 0.2
  r_sigma_length_by_length_ratio: 0.3
  r_sigma_angle: 0.1
  r_sigma_armor_lights_depth_diff: 0.2
  esekf_iter_num: 5






  
auto_aim_fsm:
  single_whole_up: 1.5 
  single_whole_down: 1.0
  whole_pair_up: 7.5 
  whole_pair_down: 6.5 #1s内至少换2次板子  2pi  否则轨迹规划无意义
  pair_center_up: 16.5
  pair_center_down: 15.0
  transfer_time: 0.5


very_aimer:
  base_yaw_offset: -0.0
  base_pitch_offset: -0.5
  sample_total_time: 1.0
  sample_horizon: 100
  fire_delay_min: 0.00
  fire_delay_max: 0.00
  max_yaw_acc: 40
  max_pitch_acc: 50
  prediction_delay: 0.00
  aim_center_more_prediction_time: 0.0
  shooting_range_h: 0.12
  shooting_range_w_small: 0.12
  shooting_range_w_large: 0.24
  min_enable_pitch_deg: 0.25
  min_enable_yaw_deg: 0.25
  ballistic_trajectory:
    gravity: 9.8
    resistance: 0.001

rune_detector:
  max_infer_num: 2
  backend: openvino
  net_detector:
    openvino:
      model_path: ${ROOT_DIR}/model/cb_rune.onnx
      device_name: "GPU"
      perf_mode: "THROUGHPUT"
      priority: "HIGH"
      # scheduling_core_type: "PCORE_ONLY"
      execution_mode: "PERFORMANCE"
      infer_request_buffer_num: 10
    tensorrt:
      model_path: ${ROOT_DIR}/model/cb_rune.onnx
      copy_context_num: 3
      min_free_mem_ratio: 0.1
      use_cuda_preproces: true
    rune_infer:
      model_type: cb
      conf_threshold: 0.2
  cv:
    bin_threshold: 100
    color_diff_thresh: 70
    rune_r_min_area: 100
    rune_r_max_area: 2000
    rune_r_1x1ratio_tol: 0.5
    rune_r_fill_ratio_min: 0.3
    rune_pan_min_area: 30
    rune_pan_max_area: 99999999
    rune_pan_cluster_radius: 70
    rune_pan_max_square_ratio: 1.3


rune_tracker:
  lost_time_thres: 2.0
  tracking_thres: 2
  esekf_iter_num: 5
  q_xyz: [0.0001, 0.0001, 0.0001]
  q_yaw: 0.1
  q_roll: 10.0
  q_a: 0.01
  q_w: 0.01
  q_tau: 0.01
  match_gate: 40.0
  voter_state_need_count: 50
  voter_mode_need_count: 20
  big_args_continue_time: 1.0
  r_sigma_pix_by_hand_length_ratio_cv: 0.05
  r_sigma_pix_by_hand_length_ratio_net: 0.2

rune_aimer:
  base_yaw_offset: -0.0
  base_pitch_offset: -0.5
  sample_total_time: 0.5
  sample_horizon: 10
  prediction_delay: -0.00
  max_yaw_acc: 40 
  max_pitch_acc: 50
  shooting_range_h: 0.12
  shooting_range_w: 0.12
  min_enable_pitch_deg: 0.25
  min_enable_yaw_deg: 0.25
  ballistic_trajectory:
    gravity: 9.8
    resistance: 0.001


camera: 
  type: daheng
  hik_camera:
    target_sn: 00DA5133320
    adc_bit_depth: Bits_8
    pixel_format: BayerRG8 #RGB8Packed
    reverse_x: false
    reverse_y: false
    width: 1440
    height: 1080
    offset_x: 0
    offset_y: 0
    acquisition_frame_rate_enable: true
    acquisition_frame_rate: 160
    exposure_time: 1700
    gain: 16.9
    gamma: 0.7 #Bayer用不了
    trigger_mode: Off
    trigger_source: ""
    trigger_activation: ""
    format: "bgr" 
    use_cuda_cvt: true
  daheng_camera:
    target_sn: FDN24040524
    pixel_format: BayerRG8
    reverse_x: false
    reverse_y: false
    width: 1440
    height: 1080
    offset_x: 0
    offset_y: 0
    acquisition_frame_rate_enable: true
    acquisition_frame_rate: 160
    exposure_time: 3500
    gain: 16.9
    gamma: 15.0
    trigger_mode: Off
    trigger_source: ""
    trigger_activation: ""
    format: "bgr"
    use_cuda_cvt: true
  mv_camera:
    frame_speed: 0
    exposure_time: 2000
    r_gain: 200
    b_gain: 150
    g_gain: 200
    # analog_gain: 100.0
    # gamma: 120
    use_cuda_cvt: true
  camera_info:
    #8mm
    image_width: 1440
    image_height: 1080
    camera_name: narrow_stereo
    camera_matrix:
      rows: 3
      cols: 3
      data: [1812.55793,    0.     ,  734.91798,
                0.     , 1810.46711,  531.77493,
                0.     ,    0.     ,    1.     ]
    distortion_model: plumb_bob
    distortion_coefficients:
      rows: 1
      cols: 5
      data: [-0.068720, 0.117810, 0.000829, 0.000523, 0.000000]
    rectification_matrix:
      rows: 3
      cols: 3
      data: [1., 0., 0.,
            0., 1., 0.,
            0., 0., 1.]
    projection_matrix:
      rows: 3
      cols: 4
      data: [1798.04639,    0.     ,  735.53338,    0.     ,
                0.     , 1801.03183,  532.11558,    0.     ,
                0.     ,    0.     ,    1.     ,    0.     ]
    #6mm

    # image_width: 1440
    # image_height: 1080
    # camera_name: narrow_stereo
    # camera_matrix:
    #   rows: 3
    #   cols: 3
    #   data: [1812.55793,    0.     ,  734.91798,
    #             0.     , 1810.46711,  531.77493,
    #             0.     ,    0.     ,    1.     ]
    # distortion_model: plumb_bob
    # distortion_coefficients:
    #   rows: 1
    #   cols: 5
    #   data: [-0.068720, 0.117810, 0.000829, 0.000523, 0.000000]
    # rectification_matrix:
    #   rows: 3
    #   cols: 3
    #   data: [1., 0., 0.,
    #         0., 1., 0.,
    #         0., 0., 1.]
    # projection_matrix:
    #   rows: 3
    #   cols: 4
    #   data: [1798.04639,    0.     ,  735.53338,    0.     ,
    #             0.     , 1801.03183,  532.11558,    0.     ,
    #             0.     ,    0.     ,    1.     ,    0.     ]
    #12mm
    # image_width: 1440
    # image_height: 1080
    # camera_name: narrow_stereo
    # camera_matrix:
    #   rows: 3
    #   cols: 3
    #   data: [3655.11292,    0.     ,  748.66803,
    #             0.     , 3648.34439,  556.97683,
    #             0.     ,    0.     ,    1.     ]
    # distortion_model: plumb_bob
    # distortion_coefficients:
    #   rows: 1
    #   cols: 5
    #   data: [-0.058763, 1.430269, 0.001191, 0.001641, 0.000000]
    # rectification_matrix:
    #   rows: 3
    #   cols: 3
    #   data: [1., 0., 0.,
    #          0., 1., 0.,
    #          0., 0., 1.]
    # projection_matrix:
    #   rows: 3
    #   cols: 4
    #   data: [3659.22949,    0.     ,  748.71496,    0.     ,
    #             0.     , 3652.02661,  556.81908,    0.     ,
    #             0.     ,    0.     ,    1.     ,    0.     ]

    #MV4mm
    # image_width: 1280
    # image_height: 1024
    # camera_name: narrow_stereo
    # camera_matrix:
    #   rows: 3
    #   cols: 3
    #   data: [1040.3717 ,    0.     ,  654.8083 ,
    #             0.     , 1040.45039,  516.48859,
    #             0.     ,    0.     ,    1.     ]
    # distortion_model: plumb_bob
    # distortion_coefficients:
    #   rows: 1
    #   cols: 5
    #   data: [-0.097818, 0.093984, 0.000866, 0.000533, 0.000000]
    # rectification_matrix:
    #   rows: 3
    #   cols: 3
    #   data: [1., 0., 0.,
    #         0., 1., 0.,
    #         0., 0., 1.]
    # projection_matrix:
    #   rows: 3
    #   cols: 4
    #   data: [1016.2797 ,    0.     ,  655.30471,    0.     ,
    #             0.     , 1021.00509,  517.31738,    0.     ,
    #             0.     ,    0.     ,    1.     ,    0.     ]