target("static_tf_bc")
set_kind("binary")
add_includedirs("static_broadcaster/include")
add_files("static_broadcaster/src/*.cpp")
add_packages("eigen")
add_deps("common_defs")
add_deps("tools")
add_packages("fmt")
add_packages("reflect-cpp")
add_packages("cxxopts")
add_packages("quill")
add_rules("iceoryx_deps")
target_end()

target("tf_agg")
set_kind("binary")
add_includedirs("transform_aggregator/include")
add_files("transform_aggregator/src/*.cpp")
add_packages("eigen")
add_deps("common_defs")
add_deps("tools")
add_packages("fmt")
add_packages("reflect-cpp")
add_packages("cxxopts")
add_packages("quill")
add_rules("iceoryx_deps")
add_rules("gtsam_deps")
target_end()

-- target("open_vins")
-- set_kind("binary")
-- add_includedirs("open_vins/include")
-- add_files("open_vins/src/*.cpp")
-- add_rules("iceoryx_deps")
-- add_deps("common_defs")
-- add_deps("tools")
-- add_packages("eigen")
-- add_packages("opencv")
-- add_packages("fmt")
-- add_packages("reflect-cpp")
-- add_packages("cxxopts")
-- add_packages("quill")
-- target_end()
