target("common_defs")
set_kind("static")
add_includedirs(".", { public = true })
add_files("src/*.cpp")
add_rules("iceoryx_deps")
add_rules("gtsam_deps")
add_packages("opencv")
add_packages("eigen")
target_end()
